### PR TITLE
Wire up the API to MLFlow registry, return masks for LabelTool

### PR DESCRIPTION
**Pull request by metazool**
Changes covered here:

* API returns predictions for input images in the same way as the tests do
* API loads the latest model from the MLFlow registry
* `scripts/train.py` registers the model after running (now needs `MLFLOW_TRACKING_URI` set in environment to register model)
* Adds a Dockerfile to run the API in a container and a docker-compose file for testing it locally (assumes MLFlow is running locally and separately, otherwise change `MLFLOW_TRACKING_URI` and remove `network_mode: host`)
* Sketch of a minimal JQuery ui to test the equivalent behaviour of LabelTool MLAssist

You will see in the compose file `/var/lib/mlflow` mounted in the API application (so it has to run somewhere that has the MLFlow shared volume. I had permissions issues when reconstructing it all locally and ended up brutally `chmod -R 777`-ing the whole of `/var/lib/mlflow` to keep moving. We won't see this in the proper setup, though.

### CODE REVIEW

**Comment by metazool** [comment]
I started sketching out a very simplified Javascript interface to look at the API results without needing to go via LabelTool. I still haven't seen this working completely end-to-end through MLAssist but felt this was more than enough change for one PR. I'll pick up the JQuery stuff separately, as it would be useful to have a quick preview mode for the fragmentation metrics as well.

**Comment by metazool** [comment]
Hi @Alex-Hall-Data - picking up on this after our period of staggered leave - would you have time to pick this one up for review during this week? You'll probably get more out of it. The test setup I had locally for the containerised API required the (internal) `docker-mlflow` project running alongside it, I remember you were interested in setting that up for local experiments. Happy to answer any questions

**Comment by Alex-Hall-Data** [comment]
Right, I'm on it. I'll need a couple of days to review it properly though since 1) I need to get the docker-mlflow project running locally, 2) I have tomorrow blocked, 3) There is a lot to review here!

**Comment by metazool** [comment]
Thanks Alex, hopefully it's not quite as bad as it looks as a) some of it is PEP8 reformatting and b) some of it (the Javascript test UI stub) isn't needed to move forward with. But it does touch quite a lot of code in bringing together the loose ends. I'm happy to spend an hour or two sitting on your shoulder for the MLFlow setup. It should be useful for your other projects,,,

**Comment by metazool** [comment]
Note about handling the failover case where the API either can't reach MLFlow or MLFlow doesn't have a model in the registry - return a 3** / 5** code?

**Comment by mobiuscreek** [comment]
If the changes make sense now we can merge, otherwise you can change or add any improvements. The api now throws a 404 if there is no model in the mlflow registry. I also made a change in the `mlflowregistry.py` so it throws an `MlflowRegistryError` if we have no models in the registry under the name we are looking for.

**Comment by metazool** [comment]
The changes make perfect sense, thankyou.

**Pull request merged**
