### PR TITLE
tweak the tests to check for imagePath (from LabelTool)

### PR DESCRIPTION
**Pull request by metazool**
LabelBox export has 'External ID' in json, LabelTool export has 'imagePath', check for both

### CODE REVIEW

**Comment by metazool** [comment]
I'll revert the test for `fit()` here and put it elsewhere, this was intended to be a small change for the labels export syntax, i had the branch open and didn't expect a can of worms

**Comment by mobiuscreek** [comment]
OK, the test logic is fine but the failing test I added was because the label masks looked black (but in fact aren't) - and yet the test was passing. The issue is from the line below: https://github.com/BritishGeologicalSurvey/CoreScore/blob/94d5b3eab3edaf2d0a05a87c5fffa3b6e7be623c/corescore/masks.py#L38 that uses grayscale colors that are not visible to the eye and has to be revisited.

**Comment by metazool** [comment]
As discussed the grayscale colours are deliberately sequential as they were in the original and the existing test is designed to establish that they are not all zero values, let me know if there is a problem with it as it stands.

I know it is a pain and if you want I can reconstruct the errors i was seeing when i tried it with non-sequential, human-visible greyscale mapping to labels. It would be good to understand it properly. It doesn't affect this PR though

**Comment by metazool** [comment]
https://forums.fast.ai/t/runtimeerror-cuda-error-device-side-assert-triggered-when-using-unet-learner/40536 - see the `sequential` branch for reproduction. " it was because I had label values in my mask that were greater than the number of classes I supplied to the learner."

**Review by mobiuscreek — APPROVED** [review]
This can be merged now and if we want to get back to the CUDA issue we have the info here.

**Pull request merged**
