### PR TITLE
Generate some metrics for rock fragments found in images

### PR DESCRIPTION
**Pull request by metazool**
This is towards #4 on calculating  a "core quality index" of core fragments identified in photographs. It's adapted slightly from the work we already had looking at the distribution of porespace in building stone thin sections.

* Also includes a sample notebook for clarity (and to continue building on the Core Quality index with @mftf in a mob session if needed?
* Added a few autopep-generated corrections on the existing tests

Note that the test cases / sample notebook is based on the manually created labels in the test cases, not yet on model-generated labels.

### CODE REVIEW

**Comment by metazool** [comment]
Hm, I thought that re-ordering the labels to set `Void` at the start of the index (as `0` is the default background value for `skimage.measure.label` would be clearer to read and involve less disturbance of data. And that would then involve retraining our model as the meaning of the predicted labels would change. But I wasn't expecting that to be flushed out in `test_acc_rock` in this way as the default `acc_rock` is explicitly looking for `LABELS.index('Void')`. Are there canned masks in the test fixtures that now have got disordered labels? (I never followed where we got the range of predicted values in that test from, and should have doublechecked harder!)

**Comment by metazool** [comment]
Ran `scripts/make_masks.py` to regenerate the masks in `Images/train_masks/` (for the sample set of cropped images from the original MSc project) and committed the results. It's these that are being used within `tests/test_model.py`. As an alternative we could regenerate the masks before running the model tests in CI, but I think it's been helpful to flush out potential data issues in this way,

**Comment by metazool** [comment]
Ok, now I look properly at this https://github.com/BritishGeologicalSurvey/CoreScore/blob/main/corescore/models.py#L66 I see that the 'Void' label, when it was at index 5, never got removed from the mask during the first test of the return from `acc_rock` (given a tensor of random values between 0 and 4); moving the 'Void' label to index 0 then _did_ have the desired effect and so the mean fell outside the expected range of results. I tweaked the test to `pytest.approx` a slightly wider range, seem reasonable? 

There is a TODO at this function, from the original project, to explore a wider range of accuracy metrics (Which you'd started discussing in #9 too) - a good range here for multi-labels from `sklearn` which might fit here better? https://docs.fast.ai/metrics.html#Multi-label-classification

**Review by mobiuscreek — COMMENTED** [review]
Good to see code being reused form other projects. The label void error was tricky to catch but hopefully the inclusion of the test helped in that respect. It's helps to get the structure right for the future tests on the rest of the metrics.

My only question would be since you introduced more metrics, is it appropriate to move `acc_rock` there now or are we talking about different metrics?

**Comment by metazool** [comment]
I think we are talking about different metrics:

* Metrics that assess how successful our model has been at recognising core fragments / semantic segmentation (#9)
* Metrics that assess, on the basis of the model's predictions for a new core photograph, how usable a core is, what kind of integrity it has (#4)

We remain confused because this PR covers _both_, but primarily the latter. There probably _is_ overlap. We could rename the main file added here to `quality.py` if it will help to avoid future confusion?

**Comment by mobiuscreek** [comment]
Yes, so to refer to the first we can call them (model)  _performance metrics_, while the latter would be (core) _quality metrics_. I agree with your suggestion. It would help to avoid confusion in the future.

**Comment by metazool** [comment]
Moved all this stuff to `quality`, plus `MEASURES` which is a cop-out but reflects where this is coming from in `skimage.measure`

It would be good to have another try with captum _after_ this (as there is a label mismatch at the moment, current `main` doesn't have Rock_Fragment_2

**Comment by mobiuscreek** [comment]
Thanks, it's more clear now. Let's merge the changes.

**Pull request merged**
